/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AListItemMeta: typeof import('@arco-design/web-vue')['ListItemMeta']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    Header: typeof import('./components/header.vue')['default']
    Home: typeof import('./components/home.vue')['default']
    IconMoonFill: typeof import('@arco-design/web-vue/es/icon')['IconMoonFill']
    IconSunFill: typeof import('@arco-design/web-vue/es/icon')['IconSunFill']
    Nav: typeof import('./components/nav.vue')['default']
    Result: typeof import('./components/result.vue')['default']
  }
}
